server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  boot:
    admin:
      client:
        url: http://localhost:6066

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://8.129.4.9:3306/db2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: yueding

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.solomon.springcloud.eitities      #所有Entity别名类所在包

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file: 'E:\8_log\Downloads/spring-boot-admin-client.log'