server:
  port: 7001

spring:
  boot:
    admin:
      client:
        url: http://localhost:6066

eureka:
  instance:
#    hostname: localhost      #eureka 服务端的实例名称
    hostname: eureka7001.com      #eureka 服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false       #是否去注册中心fetch信息，false表示自己就是注册中心，所以自己不必找自己去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file: 'E:\8_log\Downloads/spring-boot-admin-client.log'

